# Generated by Django 4.2.7 on 2024-01-07 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genrecinema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Moviename', models.CharField(max_length=255)),
                ('Genre', models.CharField(choices=[('Action', 'Action'), ('Crime', 'Crime'), ('Sports', 'Sports'), ('Fantasy', 'Fantasy'), ('Horror', 'Horror'), ('Biography', 'Biography'), ('Romance', 'Romance'), ('Sci-fi', 'Sci-Fi'), ('Thriller', 'Thriller'), ('Western', 'Western'), ('War', 'War')], max_length=10)),
                ('IMDB', models.DecimalField(decimal_places=2, max_digits=3)),
                ('Rottentomatoes', models.DecimalField(decimal_places=2, max_digits=3)),
                ('Universe', models.CharField(max_length=255, null=True)),
                ('Director', models.CharField(max_length=255)),
                ('Description', models.TextField()),
                ('date', models.DateField()),
                ('Movieimage', models.URLField(max_length=255)),
            ],
        ),
    ]
