# Generated by Django 4.2.7 on 2024-01-07 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MOVIEREC', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genrecinema',
            name='Rottentomatoes',
            field=models.DecimalField(decimal_places=0, max_digits=3),
        ),
    ]
